"""Deterministic, behavior-complete integration docs and drift checks."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

from .discovery import discover_direct_routes
from .validation import validate_manifest

MARKER = "<!-- generated by ipad_agent.lab; edit the manifest, not this file -->"


def _step_text(value: Mapping[str, Any], action_id: str, step: Mapping[str, Any], ordinal: int) -> str:
    parts = [f"{ordinal}. `{action_id}` → `{step['operation']}`"]
    selector_name = step.get("selector")
    if isinstance(selector_name, str):
        selector = value["selectors"][selector_name]
        parts.append(
            f"selector `{selector_name}` (`{selector['using']}` = `{selector['value']}`)"
        )
    if "value" in step:
        parts.append(f"value `{step['value']}`")
    if "direction" in step:
        parts.append(f"direction `{step['direction']}`")
    if "seconds" in step:
        parts.append(f"timeout `{step['seconds']}` seconds")
    return "; ".join(parts) + "."


def generate_integration_docs(manifest: str | Path | Mapping[str, Any]) -> str:
    value = validate_manifest(manifest)
    lines = [
        MARKER, f"# {value['name']} integration", "",
        f"Integration ID: `{value['id']}`. Kind: `{value['kind']}`.",
        "", "Aliases: " + ", ".join(f"`{item}`" for item in value["aliases"]) + ".",
        "", "Bundle IDs: " + ", ".join(f"`{item}`" for item in value["bundle_ids"]) + ".",
        "", "## Capabilities", "",
    ]
    lines.extend(f"- `{item}`" for item in value["capabilities"])
    lines.extend(["", "## Direct routes", ""])
    routes = discover_direct_routes(value)
    lines.extend(
        f"- `{item['action_id']}`: `{item['operation']}`" + (f" with value `{item['template']}`" if item["template"] else "")
        for item in routes
    )
    if not routes:
        lines.append("- None declared.")
    lines.extend(["", "## Selectors", ""])
    lines.extend(
        f"- `{name}` — `{recipe['using']}`: `{recipe['value']}`; cache: `{str(recipe.get('cache', False)).lower()}`."
        for name, recipe in value["selectors"].items()
    )
    if not value["selectors"]:
        lines.append("- None declared.")

    lines.extend(["", "## Actions", ""])
    action_usage = {
        action_id: [
            scenario_id for scenario_id, scenario in value["scenarios"].items()
            if action_id in scenario["actions"]
        ]
        for action_id in value["actions"]
    }
    for action_id, action in value["actions"].items():
        usage = action_usage[action_id]
        lines.extend([
            f"### `{action_id}`", "", action["description"], "",
            f"Capability: `{action['capability']}`.", "",
            "Used by scenarios: "
            + (", ".join(f"`{item}`" for item in usage) + "." if usage else "none (unused/orphan action)."),
            "", f"Safety: `{action['safety']}`. Retry: `{action['retry']}`.", "",
            "Ordered action steps:", "",
        ])
        for ordinal, step in enumerate(action["steps"], start=1):
            lines.append(_step_text(value, action_id, step, ordinal))
        lines.append("")

    lines.extend(["## Scenarios", ""])
    for scenario_id, scenario in value["scenarios"].items():
        lines.extend([
            f"### `{scenario_id}`", "", scenario["description"], "",
            "Ordered actions: " + ", ".join(f"`{item}`" for item in scenario["actions"]) + ".", "",
            "#### Ordered steps", "",
        ])
        ordinal = 1
        for action_id in scenario["actions"]:
            action = value["actions"][action_id]
            for step in action["steps"]:
                lines.append(_step_text(value, action_id, step, ordinal))
                ordinal += 1
        lines.extend(["", "#### Action policy", ""])
        for action_id in scenario["actions"]:
            action = value["actions"][action_id]
            lines.extend([
                f"- `{action_id}` — {action['description']}",
                f"  - Safety: {action['safety']}",
                f"  - Retry: {action['retry']}",
            ])
        lines.extend([
            "", f"Scenario safety: {scenario['safety']}", "",
            f"Scenario retry: {scenario['retry']}", "",
        ])

    lines.extend(["## Global retry contract", ""])
    lines.extend([
        f"Default: `{value['retry']['default']}`.", "",
        f"Maximum attempts per step: `{value['retry']['max_attempts']}`.", "",
        "Safe-repeat actions: "
        + (", ".join(f"`{item}`" for item in value["retry"]["idempotent_actions"])
           if value["retry"]["idempotent_actions"] else "none")
        + ".", "",
        "## Requirements", "",
    ])
    for field in ("host", "device", "permissions"):
        lines.append(f"### {field.title()}")
        lines.append("")
        lines.extend(f"- {item}" for item in value["requirements"][field])
        if not value["requirements"][field]:
            lines.append("- None declared.")
        lines.append("")

    compatibility = value["compatibility"]
    maximum = compatibility["maximum_os"] or "unbounded (must be evidenced)"
    lines.extend([
        "## Compatibility declaration", "",
        f"iPadOS `{compatibility['minimum_os']}` through `{maximum}`; locales: "
        + ", ".join(f"`{item}`" for item in compatibility["locales"]) + ".",
        "", f"Verification: `{compatibility['verification']}`.", "",
        "Verified app versions: "
        + (", ".join(f"`{item}`" for item in compatibility["app_versions"])
           if compatibility["app_versions"] else "none")
        + ".",
        "", "## Prohibitions", "",
    ])
    lines.extend(f"- {item}" for item in value["safety"]["prohibited"])
    if not value["safety"]["prohibited"]:
        lines.append("- None declared (completion requires an explicit review).")
    lines.extend([
        "", "## Safety and privacy", "",
        f"Classification: `{value['safety']['classification']}`. Mutates user data: `{str(value['safety']['mutates_user_data']).lower()}`.",
        "", "Required confirmations: "
        + (", ".join(value["safety"]["requires_confirmation"]) if value["safety"]["requires_confirmation"] else "none declared")
        + ".",
        "", f"Uncertain outcome: {value['safety']['uncertain_outcome']}", "",
        "Data access:", "",
    ])
    lines.extend(f"- {item}" for item in value["privacy"]["data_access"])
    if not value["privacy"]["data_access"]:
        lines.append("- None declared.")
    lines.extend(["", "Data sent:", ""])
    lines.extend(f"- {item}" for item in value["privacy"]["data_sent"])
    if not value["privacy"]["data_sent"]:
        lines.append("- None declared.")
    lines.extend([
        "", f"Retention: {value['privacy']['retention']}", "",
        f"Notes: {value['privacy']['notes']}", "",
    ])
    return "\n".join(lines)


def integration_docs(
    manifest: str | Path | Mapping[str, Any], *, output: str | Path,
    apply: bool = False, check: bool = False,
) -> dict[str, Any]:
    if apply and check:
        raise ValueError("--apply and --check are mutually exclusive")
    rendered = generate_integration_docs(manifest)
    target = Path(output).expanduser()
    current = target.read_text(encoding="utf-8") if target.exists() else None
    matches = current == rendered
    if check:
        return {"ok": matches, "checked": True, "applied": False, "target": str(target), "changed": False}
    changed = current != rendered
    if apply and changed:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
    return {
        "ok": True, "checked": False, "applied": apply, "target": str(target),
        "changed": bool(apply and changed), "preview": rendered,
    }


check_integration_docs = integration_docs

__all__ = ["MARKER", "check_integration_docs", "generate_integration_docs", "integration_docs"]
